# This rule is not used by the project mysql-service-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the database.mycompany.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlservice-editor-role
rules:
- apiGroups:
  - database.mycompany.org
  resources:
  - mysqlservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mycompany.org
  resources:
  - mysqlservices/status
  verbs:
  - get
