# This rule is not used by the project mysql-service-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to database.mycompany.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlservice-viewer-role
rules:
- apiGroups:
  - database.mycompany.org
  resources:
  - mysqlservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.mycompany.org
  resources:
  - mysqlservices/status
  verbs:
  - get
