global: {evaluation_interval: 30s, scrape_interval: 30s, scrape_timeout: 10s}
scrape_configs:
- job_name: myapp
  metrics_path: /metrics
  static_configs:
  - targets: ['mysql.default.svc:9104']
- job_name: mysql-app-01-mysql-1
  metrics_path: /metrics
  static_configs:
  - targets: ['mysql-mysql-1.app-01.svc:9104']
